baseurl = "http://marinagioelesposi.github.io"
title = "Marina e Gioele"
theme = "dimension"
languageCode = "it"
defaultContentLanguage = "it"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  title = "Marina e Gioele sposi"
  description = "Questo e' il sito del nostro matrimonio"
  logo = "fa-diamond"
  copyright = "Gioele La Manno e Marina Micari"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "google"
  icon = "google"
  link = "marinagioelesposi@gmail.com"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[languages]
[languages.it]
languageName = "Clicca qui per sito in Italiano"
weight = 1


[languages.en]
languageName = "Click here for English"
weight = 2
title = "Marina and Gioele wedding"
description = 'This is the website of our wedding'


